[tasks.build-all]
script = '''
    cd derive_macro
    cargo build
    cd ..
    cargo build
'''

[tasks.debug]
script_runner="powershell"
script = '''
cd derive_macro
env RUSTFLAGS=-Awarnings cargo build --quiet
cd ..
env RUSTFLAGS=-Awarnings cargo run --bin enum_iter_derive --quiet
'''

[tasks.lint]
script_runner = "powershell"
script = '''
cargo clippy
'''
